FROM alpine:latest

ARG VER="2020.08.2"
LABEL rakuversion=$VER

ENV PATH="/root/raku-install/bin:/root/raku-install/share/perl6/site/bin:/root/.rakudobrew/bin:${PATH}" \
    PKGS="curl git libuuid gcc build-base sqlite sqlite-dev" \
    PKGS_TMP="perl curl-dev linux-headers wget" \
    ENV="/root/.profile"

RUN mkdir /home/raku \
    && apk update && apk upgrade \
    && apk add --no-cache $PKGS $PKGS_TMP \
    && git clone https://github.com/tadzik/rakudobrew ~/.rakudobrew \
    && eval "$(~/.rakudobrew/bin/rakudobrew init Sh)"\
    && rakudobrew build moar $VER --configure-opts='--prefix=/root/raku-install' \
	&& rm -rf /root/.rakudobrew/versions/moar-$VER \
	&& rakudobrew register moar-$VER /root/raku-install \
    && rakudobrew global moar-$VER \
    && rakudobrew build-zef \
    && zef install Linenoise App::Prove6 

# More packages
RUN zef install --/test Cro
RUN zef install LibUUID

RUN apk del $PKGS_TMP
RUN rm -rf /root/.rakudobrew /root/raku-install/zef

# Runtime
WORKDIR /home/raku
CMD ["tail", "-f", "/dev/null"]
