FROM debian:bullseye-slim
RUN apt-get update
ARG BUILD_PKGS="wget git build-essential"
RUN apt-get install -y ${BUILD_PKGS}
ARG RAKU_HOME=/home/raku
RUN mkdir ${RAKU_HOME}
ENV PATH="${RAKU_HOME}/bin:${RAKU_HOME}/share/perl6/site/bin:${PATH}"
WORKDIR /root
ARG RAKU_DIR=rakudo-moar-2021.02.1-01-linux-x86_64-gcc
ARG RAKU_TGZ=${RAKU_DIR}.tar.gz
ARG RAKU_DL=https://rakudo.org/dl/rakudo/${RAKU_TGZ}
RUN wget ${RAKU_DL}
RUN tar -xf ${RAKU_TGZ}
RUN mv ${RAKU_DIR}/* ${RAKU_HOME}/.
RUN rm *.gz
RUN rm -rf ${RAKU_DIR}

# Testing
RUN zef install Linenoise App::Prove6

# UUID
RUN apt-get install -y libuuid1
RUN zef install LibUUID

# Cro
RUN apt-get install -y libssl-dev
RUN zef install --/test cro

# Crypt
RUN apt-get install -y libgcrypt20 libgcrypt20-dev
RUN zef install Base64::Native
RUN zef install Gcrypt

# DB
RUN apt-get install -y sqlite3 libsqlite3-dev libpq5 libpq-dev
RUN zef install DBIish
RUN zef install File::Directory::Tree

# OO Monitors
RUN zef install OO::Monitors

# Logging
RUN zef install Log::Async

# Curl
RUN apt-get install libcurl4 libcurl4-openssl-dev
RUN zef install LibCurl

# JSON
RUN zef install JSON::Fast

# Cro Testing
RUN  zef install Cro::HTTP::Test

RUN apt-get purge -y ${BUILD_PKGS}
RUN apt-get clean

# Runtime
WORKDIR /home/raku
CMD ["tail", "-f", "/dev/null"]
